- name: Deploy Monitoring Stack on EKS with NGINX Ingress
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars/main.yml

  tasks:

    - name: Create Ingress namespace
      kubernetes.core.k8s:
        state: present
        kind: Namespace
        name: "{{ ingress_namespace }}"

    - name: Deploy NGINX Ingress Controller
      kubernetes.core.helm:
        name: "{{ nginx_release_name }}"
        chart_ref: "{{ nginx_chart }}"
        release_namespace: "{{ ingress_namespace }}"
        values: "{{ lookup('template', 'templates/nginx-values.yaml.j2') | from_yaml }}"
        create_namespace: false
        update_repo_cache: false

    - name: Create Monitoring namespace
      kubernetes.core.k8s:
        state: present
        kind: Namespace
        name: "{{ monitoring_namespace }}"

    - name: Deploy kube-prometheus-stack
      kubernetes.core.helm:
        name: "{{ monitoring_release_name }}"
        chart_ref: "{{ monitoring_chart }}"
        release_namespace: "{{ monitoring_namespace }}"
        create_namespace: false
        update_repo_cache: false

    - name: Apply Monitoring Ingress
      kubernetes.core.k8s:
        state: present
        namespace: "{{ monitoring_namespace }}"
        src: "files/{{ ingress_file }}"
